#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Doc/Views/DocInformationView/_/Edit.cshtml")]
    public partial class _Areas_Doc_Views_DocInformationView___Edit_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Doc_Views_DocInformationView___Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="编辑文档";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/Doc/DocInformationView/Edit\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_CatalogID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_CatalogID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">类型：</td><td>&nbsp;\r\n\r\n<input");

WriteLiteral(" id=\"CatalogID\"");

WriteLiteral(" name=\"CatalogID\"");

WriteAttribute("url", Tuple.Create(" url=\"", 846), Tuple.Create("\"", 906)
, Tuple.Create(Tuple.Create("", 852), Tuple.Create("/api/Doc/DocCatalog/EditTree?&Value=", 852), true)
            
            #line 22 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
  , Tuple.Create(Tuple.Create("", 888), Tuple.Create<System.Object, System.Int32>(Model.CatalogID
            
            #line default
            #line hidden
, 888), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 907), Tuple.Create("\"", 933)
            
            #line 22 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
                             , Tuple.Create(Tuple.Create("", 915), Tuple.Create<System.Object, System.Int32>(Model.CatalogID
            
            #line default
            #line hidden
, 915), false)
);

WriteLiteral(" style=\"width: 200px\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var CatalogID_Value = \'");

            
            #line 24 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
                       Write(Model.CatalogID);

            
            #line default
            #line hidden
WriteLiteral(@"';
    jQuery(function() {
        jQuery('#CatalogID').combotree(
        {
            onLoadSuccess:function(node, data) {
                jQuery('#CatalogID').combotree('setValue',CatalogID_Value);
            }
        });
    });
</script>
</td></tr>
<tr");

WriteLiteral(" id=\"Container_Title\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Title\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">标题：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Title\"");

WriteLiteral(" name=\"Title\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1430), Tuple.Create("\"", 1452)
            
            #line 36 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1438), Tuple.Create<System.Object, System.Int32>(Model.Title
            
            #line default
            #line hidden
, 1438), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"200\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_InfoNo\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_InfoNo\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">文档编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"InfoNo\"");

WriteLiteral(" name=\"InfoNo\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1672), Tuple.Create("\"", 1695)
            
            #line 39 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1680), Tuple.Create<System.Object, System.Int32>(Model.InfoNo
            
            #line default
            #line hidden
, 1680), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_InfoType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_InfoType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">信息类型：</td><td>&nbsp;\r\n");

            
            #line 42 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_InfoType, "InfoType", Model.InfoType, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_FilePath\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_FilePath\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">主文：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"FilePath\"");

WriteLiteral(" name=\"FilePath\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2134), Tuple.Create("\"", 2159)
            
            #line 45 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2142), Tuple.Create<System.Object, System.Int32>(Model.FilePath
            
            #line default
            #line hidden
, 2142), false)
);

WriteLiteral("  class=\"easyui-validatebox\"");

WriteLiteral(" style=\"width: \"");

WriteLiteral("/>&nbsp;\r\n<input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" id=\"Upload_FilePath\"");

WriteLiteral(" name=\"Upload_FilePath\"");

WriteLiteral(" />\r\n<input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnFilePath_Upload\"");

WriteLiteral(" name=\"btnFilePath_Upload\"");

WriteLiteral(" value=\"上传\"");

WriteLiteral(" onclick=\"btnFilePath_UploadClick()\"");

WriteLiteral("/>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n       ///上传按钮事件\r\n       function btnFilePath_UploadClick(){\r\n            jQue" +
"ry(\"#myForm\").ajaxSubmit( {\r\n                type: \'post\',\r\n                data" +
"Type: \'json\',\r\n                url: \"/api/SiteManage/UploadFile/Upload?FieldName" +
"=FilePath&UploadFieldName=Upload_FilePath&ModelID=DocInformationView&ModuleID=Do" +
"c\",\r\n                beforeSubmit:  function(formData, jqForm, options) {\r\n     " +
"               var queryString = jQuery.param(formData);\r\n                    if" +
"( jQuery(\"Upload_FilePath\").val()==\"\"){\r\n                        alert(\"请选择你要上传的" +
"文件！\");\r\n                    }\r\n                    return true;\r\n               " +
" },\r\n                success: function(result) {\r\n                  // alert(msg" +
");\r\n                  // eval(\"var result=\"+msg);\r\n                   if(result." +
"Status==1){\r\n                        jQuery(\"#FilePath\").val(result.returnValue)" +
";\r\n                        //deleteFile(\"Upload_FilePath\");\r\n                   " +
"     alert(\"上传成功\")\r\n                   }else{\r\n                        alert(res" +
"ult.returnValue);\r\n                   }\r\n                },\r\n                err" +
"or: function(error) {\r\n                    //alert(error);\r\n                }\r\n " +
"          });\r\n        }\r\n       \r\n\r\n            /**\r\n        * file,input type=" +
"file 的name\r\n        **/ \r\n        function deleteFile(file){\r\n           var ie " +
"= (navigator.appVersion.indexOf(\"MSIE\")!=-1);//IE \r\n           var ff = (navigat" +
"or.userAgent.indexOf(\"Firefox\")!=-1);//Firefox \r\n\r\n           if(ie)\r\n          " +
"  clearIEFileValue(jQuery(\"input[name=\"+file+\"]\")[0]);\r\n           else\r\n       " +
"     jQuery(\"input[name=\"+file+\"]\").attr(\"value\",\"\"); //FF\r\n        }\r\n        /" +
"/清空上传控件的值，obj为上传控件对象\r\n        function clearIEFileValue(obj) {\r\n            obj." +
"select();\r\n            document.execCommand(\"delete\");\r\n        }\r\n</script></td" +
"></tr>\r\n<tr");

WriteLiteral(" id=\"Container_HtmlContent\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_HtmlContent\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">内容：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"HtmlContent\"");

WriteLiteral(" name=\"HtmlContent\"");

WriteLiteral(" style=\"width:600px;height:350px\"");

WriteLiteral(">");

            
            #line 100 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
                                                                           Write(Model.HtmlContent);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n<script");

WriteLiteral(" src=\"/Resources/JsLib/ueditor/ueditor.config.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Resources/JsLib/ueditor/ueditor.all.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Resources/JsLib/ueditor/lang/zh-cn/zh-cn.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(function() {\r\n        UE.getEditor(\'HtmlContent\');\r\n    });\r\n</script></" +
"td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_FileList\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_FileList\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">附件：</td><td>&nbsp;<div");

WriteLiteral(" id=\"FieldDIV_FileList\"");

WriteLiteral("></div>\r\n<style>\r\n    .file-row span {\r\n        float: left;\r\n    }\r\n</style>\r\n<l" +
"ink");

WriteLiteral(" href=\"/Resources/JsLib/dropzone/dropzone.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/Resources/JsLib/dropzone/basic.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral("/>\r\n<script");

WriteLiteral(" src=\"/Resources/JsLib/dropzone/dropzone.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/Static/v1/js/jQuery.batchFileUpload.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    jQuery(function() {
        jQuery('#FieldDIV_FileList').batchFileUpload({
            UploadFieldName: 'FileList',
            FieldName: ""FileList"",
            ModelID: 'DocInformationView',
            ModuleID: 'Doc',
            Value: '");

            
            #line 126 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
               Write(Model.FileList);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n        });\r\n    });\r\n</script></td></tr>\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"InfoID\"");

WriteLiteral("  name=\"InfoID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5670), Tuple.Create("\"", 5693)
            
            #line 130 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5678), Tuple.Create<System.Object, System.Int32>(Model.InfoID
            
            #line default
            #line hidden
, 5678), false)
);

WriteLiteral("/>\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 133 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
   Write(RenderPage("~/Areas/Doc/Views/DocInformationView/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
jQuery('input[name=InfoType]').bind('click', CheckConditions);
function CheckConditions(){
//if((IsInCheckBox(document.myForm.InfoType,'1')||IsInCheckBox(document.myForm.InfoType,'1'))){
//jQuery('#Container_FilePath').show();
//} 
//else{ 
//jQuery('#Container_FilePath').hide();
//} 
if((IsInCheckBox(document.myForm.InfoType,'2')||IsInCheckBox(document.myForm.InfoType,'2'))){
jQuery('#Container_HtmlContent').show();
} 
else{ 
jQuery('#Container_HtmlContent').hide();
} 
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 174 "..\..\Areas\Doc\Views\DocInformationView\_\Edit.cshtml"
Write(RenderPage("~/Areas/Doc/Views/DocInformationView/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
